version: "3.0"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: mysql://dev:ciscocisco@mysql:3306/dev
      PORT: "8080"
      DEV: "true"

  mysql:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: &DATABASE_ROOT_PASSWORD "ciscocisco"
      MYSQL_DATABASE: &DATABASE_NAME "dev"
      MYSQL_USER: &DATABASE_USER "dev"
      MYSQL_PASSWORD: &DATABASE_PASSWORD "ciscocisco"